# Generated by Django 3.2.4 on 2021-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='snippet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='tite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
